[package]
name = "rust_regio"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ddo = { git = "https://github.com/xgillard/ddo" }
fixedbitset = "0.4.2"
fxhash = "0.2.1"
